### ISSUE TITLE
pTeX への \ucs 追加に対応

### ISSUE THREAD

**Issue by aminophen** [zr-tex8r/ifptex#1]
私が忘れそうなので，書いておきます。

ifptex パッケージが \ucs の存在だけで upTeX と判定するため

> pTeX を upTeX だと誤判定するのみならず，返り値を -1 に変更した影響で upTeX でも ! Invalid KANSUJI char (-1). のエラーが出るようです）

https://github.com/texjporg/tex-jp-build/pull/121#issuecomment-869740134

**Comment by zr-tex8r** [comment]
0d239f6782d116624ec79ddc8e4abb399b581570 の修正：

* もし`\ptexversion`プリミティブがあるなら：
    * \uptexversion`プリミティブがあるならupTeX、ないならpTeX。
* それ以外は、従来の動作を維持。

コレでいいのかな？🤔

**Comment by aminophen** [comment]
大丈夫そうです。

**Comment by aminophen** [comment]
> 返り値を -1 に変更した影響で upTeX でも ! Invalid KANSUJI char (-1). 

こっちは何が起きているのか私にはわかりません…。

```
! Invalid KANSUJI char (-1).
<to be read again> 
                   \relax 
l.309 ...4E\J/6524\J/3565\J/633C\J/6563\X/89\X/3D}
                                                  
?
```

**Comment by zr-tex8r** [comment]
この辺りのコード、

```tex
\@nameuse{漢字コード=UTF-8}
```

のように書いておくと入力漢字コードがUTF-8でない場合に警告する（ただし`\epTeXinputencoding`があるならutf8に設定する）、という機能のためのもの。

だけど、どうやら「inputencが有効な場合は失敗する」という問題があるようで、今のLaTeXだと既定でinputencが有効だから全く機能しない🙃

これはもう廃止だな 🙃🙃🙃

**Comment by zr-tex8r** [comment]
36fc1a864516c331428bf676fc89d476e8be2b68 でグッバイ👋 

ちなみにエラーの直接の原因は

```tex
\kansujichar1=\jis"2F4E % 未定義符号位置, 結果が0から-1に変わった
```

で、これが通らないのは意図通りでしょう。

**Comment by aminophen** [comment]
v2.1 が TeX Live に来ました。ありがとうございました。
